version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      BASE_MESSAGES_URL: "https://owpublic.blob.core.windows.net/tech-task/messages/current-period"
      BASE_REPORTS_URL: "https://owpublic.blob.core.windows.net/tech-task/reports"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ./src:/app/src
    environment:
      PYTHONPATH: "/app/src"
      BASE_MESSAGES_URL: "https://owpublic.blob.core.windows.net/tech-task/messages/current-period"
      BASE_REPORTS_URL: "https://owpublic.blob.core.windows.net/tech-task/reports"
    command: ["pytest", "--maxfail=1", "--disable-warnings"]
